name: Bundle and Deploy

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

concurrency:
  group: ${{github.ref}}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bundle-deploy:
    name: Bundle and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: bundles
